### ISSUE TITLE
DOI Search updates per testing

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-wds-react#10]
@jordanpadams commented on [Thu Nov 18 2021](https://github.com/NASA-PDS/pds-doi-ui/issues/104)

- [x] **Hover/clickable info icon next to `Status`** indicating what the various status-es mean.
- [x] **Add margin to right of table** - status column gets covered a bit by the feedback widget.
- [X] ~**Identifiers should be LIDVID for PDS4 and data set id for PDS3** - I think this is possible from the data, but we want to display the data set ID if at all possible. the PDS4-equivalent identifier doesn't make sense to anyone outside of JPL~ - DOI Service thing. Separate ticket created.
- [x] **Only rows with Status = Findable should have links** - Registered/Draft means they are not online
- [x] **Change page title from "PDS: Tools" to "PDS: DOI Search"**
- [ ] **How to translate data set IDs with a slash for search** - data set ID search does not work if they have a slash in the data set id
- [x] **searches need to be case insensitive**
- [X] ~**sortable by each columns**~ - DOI API needs to be updated. Separate ticket created.

---

@tloubrieu-jpl commented on [Thu Nov 18 2021](https://github.com/NASA-PDS/pds-doi-ui/issues/104#issuecomment-973031746)

@jordanpadams I would move the frontend ticket to pds-wds-react since the module will stay there.

**Comment by eddiesarevalo** [comment]
_**Identifiers should be LIDVID for PDS4 and data set id for PDS3** - I think this is possible from the data, but we want to display the data set ID if at all possible. the PDS4-equivalent identifier doesn't make sense to anyone outside of JPL_ 
@jordanpadams 
Should this be changed from the server side? Here is the content for a single search result:
```javascript
{
   doi: "10.17189/1517634" 
   identifier: "urn:nasa:pds:maven.rose.raw:data.tnf::1.8" 
   node: "ppi" 
   status: "findable" 
   submitter: "pds-operator@jpl.nasa.gov"
    title: "MAVEN ROSE Radio Science Tracking and Navigation File (TNF) Data Collection"
    update_date: "2020-06-13T00:02:07+08:00"
}
```
Either the identifier should be changed depending on if the product is PDS4 or PDS3. Or we can add another field called `data_set_id` that if the search result is PDS3, it will be populated with the data set ID



_**Change page title from "PDS: Tools" to "PDS: DOI Search"**_
@jordanpadams This was changed from pds-gamma website so there is no record on github. 
Is this image what you had in mind for the title?
![Screen Shot 2021-12-06 at 3 27 05 PM](https://user-images.githubusercontent.com/5596893/144938989-f9131cb8-31a9-4b50-aea6-7deba452b88d.png)



_**How to translate data set IDs with a slash for search** - data set ID search does not work if they have a slash in the data set id_
@jordanpadams Do you happen to have an example of this? I tried https://pds-gamma.jpl.nasa.gov/tools/doi/#/search/10.17189/1517634 and it returns the result.



_**searches need to be case insensitive**_
@jordanpadams I can do a quick fix for this by just making all search text to lower case but that might not return the correct results. The server side should probably do the logic to find the right results.



_**sortable by each columns**_
@jordanpadams @collinss-jpl 
Is there a way to do this easily on the server side? For example something like `&sort=title desc` 
If not I can do this client side but the logic might be more complex as the returned json result array has to be sorted which would mess with the pagination.

**Comment by jordanpadams** [comment]
@eddiesarevalo 

> _**Identifiers should be LIDVID for PDS4 and data set id for PDS3** - I think this is possible from the data, but we want to display the data set ID if at all possible. the PDS4-equivalent identifier doesn't make sense to anyone outside of JPL_ @jordanpadams Should this be changed from the server side? Here is the content for a single search result:

> 
> Either the identifier should be changed depending on if the product is PDS4 or PDS3. Or we can add another field called `data_set_id` that if the search result is PDS3, it will be populated with the data set ID

we can table this for now. we may need to get this data added to the metadata in the service

> 
> _**Change page title from "PDS: Tools" to "PDS: DOI Search"**_ @jordanpadams This was changed from pds-gamma website so there is no record on github. Is this image what you had in mind for the title?

I was talking about this:
<img width="283" alt="Screen Shot 2021-12-06 at 7 58 36 PM" src="https://user-images.githubusercontent.com/33492486/144963744-97fddc75-219d-4493-a6fa-3e6ea5b6893b.png">

but it doesn't really matter.

> 
> _**How to translate data set IDs with a slash for search** - data set ID search does not work if they have a slash in the data set id_ @jordanpadams Do you happen to have an example of this? I tried https://pds-gamma.jpl.nasa.gov/tools/doi/#/search/10.17189/1517634 and it returns the result.

This does not work: https://pds-gamma.jpl.nasa.gov/tools/doi/#/search/CO-V/E/J/S/SS-RPWS-3-RDR-LRFULL-V1.0 . The slashes in the data-set-id should probably just be translated to `*`, e.g. https://pds-gamma.jpl.nasa.gov/tools/doi/#/search/co-v*e*j*s*ss-rpws-3-rdr-lrfull-v1.0 (note: the current DOI service on pds-gamma does not contain the fix for handling upper case)

> 
> _**searches need to be case insensitive**_ @jordanpadams I can do a quick fix for this by just making all search text to lower case but that might not return the correct results. The server side should probably do the logic to find the right results.

This has been updated already, it just needs to be deployed. @collinss-jpl @tloubrieu-jpl once we get the latest bug fixes in, can we upgrade the DOI Service on pds-gamma?

> 
> _**sortable by each columns**_ @jordanpadams @collinss-jpl Is there a way to do this easily on the server side? For example something like `&sort=title desc` If not I can do this client side but the logic might be more complex as the returned json result array has to be sorted which would mess with the pagination.

copy that. let's table this functionality to a later upgrade

**Comment by collinss-jpl** [comment]
@jordanpadams @eddiesarevalo @tloubrieu-jpl I've just created a `release/2.1.1` branch and will try to get the service on gamma updated today so the case-insensitive search is available.

**Comment by collinss-jpl** [comment]
> @jordanpadams @eddiesarevalo @tloubrieu-jpl I've just created a `release/2.1.1` branch and will try to get the service on gamma updated today so the case-insensitive search is available.

Service has been updated to 2.1.1 on pds-gamma, and the DOI API has been restarted. Let me know on slack if you run into any issues.

**Comment by jordanpadams** [comment]
@eddiesarevalo on additional update if possible:
- [ ] trim input search - When putting `   urn:nasa:pds:insight-ifg-mars:document:insight-ifg-data-calibration-description::2.0` into search, it does not work. simple left trim/right trim of spaces would be great

**Comment by jordanpadams** [comment]
@eddiesarevalo are the changes above done and merged? or are they still on a branch?

**Comment by eddiesarevalo** [comment]
@jordanpadams Everything was pushed up except for the trim edge whitespace, which I just pushed up. This is all in a branch https://github.com/NASA-PDS/pds-wds-react/commits/embed-and-npm-builder

**Comment by nutjob4life** [comment]
Moving to review

**Comment by jordanpadams** [comment]
@eddiesarevalo can we create a PR so we can merge this to main? or are we not doing that just yet?

**Comment by eddiesarevalo** [comment]
@jordanpadams We need to think about what to do with the current main. It is completely different and contains the "PDS App Bar" We should probably add the PDS app bar to this repo.

**Comment by jordanpadams** [comment]
@eddiesarevalo copy that. lets talk about it at the breakout.
