### ISSUE TITLE
As a DOI Search user, I want to be able to find a parent data set DOI from a product identifier

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds-react#12]
## 💪 Motivation
...so that I can get the DOI associated with a particular product, which will most likely be the parent bundle/collection

## ⚖️ Acceptance Criteria
**Given** a running DOI search
**When I perform** a search with a product LIDVID (e.g. `urn:nasa:pds:insight_cameras:data:d014l0122_607341680rus_g0103_0100m::8.0`)
**Then I expect** to get the parent collection DOI (e.g. the DOI for `urn:nasa:pds:insight_cameras:data` which is `10.17189/1510488`)

## ⚙️ Engineering Details

ultimate goal: when someone searches by LIDVID that we can't find a match, we walk up to the parent data sets until we come to 1 or more DOIs and display in new section `Parent Data Set DOI(s)` below `No record(s)...` (which I think we should keep to show there was no exact match).

### Algorithm
Here is what I think we need to do:
1. if no results come back, parse the search query to detect a collection or product LID / LIDVID (`urn:nasa:<agency>:<bundle_id>:<collection_id>:<product_id>::<version_id>`)
2. if it is a product LID(VID), let's chop off the product_id/version_id, and query for the collection (`*urn:nasa:<agency>:<bundle_id>:<collection_id>::*`)
3. if it is a collection LID(VID) and no results come back, let's chop off the collection_id/version_id, and query for the bundle (`*urn:nasa:<agency>:<bundle_id>::*`)

NOTE: More than one DOI may be returned when searching by collection/bundle LID. Display both for now.

**Comment by jordanpadams** [comment]
@eddiesarevalo on pds-gamma when i search for `urn:nasa:pds:insight_cameras:data:c000m0000_596533559edr_f0000_0106m`, it says no DOIs found. But it should return `urn:nasa:pds:insight_cameras:data`?

**Comment by nutjob4life** [comment]
Going back & forth with @jordanpadams; the comment above ↑ has been addressed and if he thinks it's okay, then it's _all good!_

**Comment by jordanpadams** [comment]
@eddiesarevalo this looks good. per my comment on the other DOI ticket, my only concern is all of this work is on a branch. can you drop in the referenced commit so we at least have some traceability to the implementation?

**Comment by eddiesarevalo** [comment]
@jordanpadams The commit hadn't been pushed up. Sorry about that. It should show now: https://github.com/NASA-PDS/pds-wds-react/commit/ebc1f6671b4e9c654b3944db7cc7a1dd9f507e95
