### ISSUE TITLE
Improve Search UI Behavior For DOI Search Widget

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds-react#15]
Search behavior: IIRC, the latest decision regarding the default view for the Search page is that it's not supposed to display any results until the search button (or enter from the search bar) is entered.

Search behavior: clicking the 'X' in the search bar to clear the search - should this clear the results as well as the text in the search bar?

Remove the uneven underlines on the results table.

See https://github.com/NASA-PDS/pds-doi-ui/issues/68

**Comment by jordanpadams** [comment]
closing since it is tracked via tickets above. will have broader merge to main later
