### ISSUE TITLE
Update DOI Service per user feedback

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds-react#22]
## 💡 Description

- [x] Update wording for results returned per parent DOIs. For example, https://pds-gamma.jpl.nasa.gov/tools/doi/#/search/urn:nasa:pds:mars2020.spice:1.0 returns:

<img width="1218" alt="Screen Shot 2022-01-06 at 2 50 07 PM" src="https://user-images.githubusercontent.com/33492486/148463355-0f60ee1a-da91-45f3-874f-ebdb52b8dcf0.png">

which can be somewhat counterintuitive. Instead let's say in the error message "No exact match(es) found."

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo can you write here in comment how it has been done (commit number, deployments of the update) ?

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl The commit was #22
Deployment is in the latest of npm beta: https://www.npmjs.com/package/@nasapds/pds-wds-react/v/0.0.2-beta.3
That npm package has also been added to the doi ui.

**Comment by tloubrieu-jpl** [comment]
Ok, thanks @eddiesarevalo I missed that you had the ticket number in the commit, which is a very good practice.
