### ISSUE TITLE
Update NPM Package documentation and fix NPM package upload artifacts

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds-react#24]
## 💡 Description

Follow-on to https://github.com/NASA-PDS/pds-wds-react/issues/8, update documentation that appears here: https://www.npmjs.com/package/@nasapds/pds-wds-react.

Also fix uploading of Javascript embed files

**Comment by eddiesarevalo** [comment]
Updates can be seen at https://www.npmjs.com/package/@nasapds/pds-wds-react

**Comment by jordanpadams** [comment]
Closed per comments above and https://github.com/NASA-PDS/pds-wds-react/commit/3b9723dbe9726cf2778efee16d974ef2cafab31f
