### ISSUE TITLE
Add Search DOI Component

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/pds-wds-react#4]
Add search DOI component to the library on embed-and-npm-builder branch.

**Comment by eddiesarevalo** [comment]
Here is an example of a create-react-app index page that runs the DoiSearch widget:
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import reportWebVitals from './reportWebVitals';
import {DoiSearch} from 'pds-wds-react';


ReactDOM.render(
  <React.StrictMode>
    <DoiSearch/>
  </React.StrictMode>,
  document.getElementById('root')
);

reportWebVitals();
```

**Comment by tloubrieu-jpl** [comment]
i have been able to run all the tests. No merge request since there are some challenges in merging with the preexisting code in main see ticket #6
