### ISSUE TITLE
Some findable product do not have links in the search results

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-wds-react#5]
## 🐛 Describe the bug
Duplicate of bug NASA-PDS/pds-doi-ui#99 but this needs to be corrected in the repository as well

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl This was added in https://github.com/NASA-PDS/pds-wds-react/commit/86e99b860dfa7ddeb7517dce4a2696ba07b3d2d2 a while back.

**Comment by jordanpadams** [comment]
closing per comment ☝️
