### ISSUE TITLE
Create a NPM package

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-wds-react#8]
- [x] Remove all unbuilt code from the upload to minimize the size of the package. Only the neccesary code should be uploaded to npm.
- [x] Update package json with pds values such as title, github page, etc.
- [x] Use Semantic versioning to match react packaging
- [x] Upload to NPM site under our account
- [ ] Test that it can be downloaded and installed into a new react web app.
- [ ] Write up documentation for npm site.

**Comment by jordanpadams** [comment]
descoping from this sprint for other bug fixes and improvements that are higher priority in blocking issues.

**Comment by eddiesarevalo** [comment]
- [ ] Remove all unbuilt code from the upload to minimize the size of the package. Only the neccesary code should be uploaded to npm.
- [ ] Use Semantic versioning to match react packages.
- [ ] Write up documentation for npm site.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo is waiting for the npm organization password from @tloubrieu-jpl

**Comment by eddiesarevalo** [comment]
Published to https://www.npmjs.com/package/@nasapds/pds-wds-react

The documentation needs to be updated and unnecessary built files need to be removed.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo this is unclear to me where the source for that is, Is it on a branch of pds-wds-react repository ?

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl It is here: https://github.com/NASA-PDS/pds-wds-react/tree/npm-package-build
This will merge back into the embed-and-npm-builder branch once the integration with the doi ui is finished. Then we can make embed-and-npm-builder into main.
