### ISSUE TITLE
As a developer, I want to update the DOISearch component backend url in an attribute

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-wds-react#9]
## 💪 Motivation
...so that I can swithc backend url easily

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
@eddiesarevalo just checking, has this been completed?

**Comment by eddiesarevalo** [comment]
@jordanpadams Yes, this was added in https://github.com/NASA-PDS/pds-wds-react/commit/86e99b860dfa7ddeb7517dce4a2696ba07b3d2d2

To update the endpoint url in react you can use: `<DoiSearch api="">`

To update the endpoint url in javascript build you can use: `<div id="DoiSearch" data-api=""></div>`
